# Generated by Django 4.1.4 on 2023-01-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Cantidad',
        ),
    ]
